/**
 * syslogd 's Default log file, use syslogd.
 * Default: /var/log
 */

#include <syslog.h>
int main(int argc, char **argv)  
{  
	openlog("MyMsgMARK", LOG_CONS | LOG_PID, 0);  
	syslog(LOG_EMERG,  
			"This is a syslog test message generated by program '%s'/n",  
			argv[0]);  
	closelog();  
	return 0;  
}  
#if 0
int main(int argc, const char *argv[])
{
	syslog(LOG_ERR,"hello world!!");
	return 0;
}
#endif
