
all: var_start var_start1 var_start2 test1

var_start:
	gcc ./var_start.c -o var_start
var_start1:
	gcc ./var_start1.c -o var_start1
var_start2:
	gcc ./var_start2.c -o var_start2
test1:
	gcc ./test1.c -o test1

clean:
	rm var_start var_start1 var_start2 test1
